config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

  resource :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews

  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews
  has_many :product, through: :reviews

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("Lower(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all
    end

    respond_to do |format|
      format.html
      format.js
    end


  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_url(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only:[:create, :destroy]

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to product_url(@product.id), notice: 'Review added.'}
        format.js {}
      else
        format.html { render 'products/show', alert: 'There was an error' }
        format.js {}
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

<%= yield %>

  <p class="userinfo">
    <% if current_user %>
      Signed in as <%= current_user.email %>, <%= link_to "Log out", sessions_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log in", new_sessions_path %> or <%= link_to "Sign up", new_users_path %>
    <% end %>
  </p>

</body>
</html>

app/views/products/_error.html.erb
<% if @review.errors.any? %>
  <div id="error_explanaton">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
      <div class="alert">

        <%= msg %>
      </div>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :price_in_cents %><br />
  <%= f.text_field :price_in_cents %>
</div>
<div class="field">
  <%= f.label :description %><br />
  <%= f.text_field :description %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count,"erorr") %> prohibited this product from being saved:</h2>
    <ul>
      <% @product.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<p>
  <%=link_to product.name, product_path(product) %>, $<%= product.formatted_price%>
</p>
<p>
  <%= product.description %>
</p>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <div class="review">

    <p class="comment">
      <%= review.comment %>
    </p>
      <br>

    <div class="poster">
      <% if review.user != nil %>
        <em> by <%= review.user.email %></em>
        Added on: <%= review.created_at %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

<%= render 'form' %>

<%= link_to "Back to Product", product_path(@product)%>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>





<%= link_to "New Product", new_product_path %>


<div id="products">
  <%= render @products %>
</div>

app/views/products/index.js.erb
$('#products').html("<%= j(render @products) %>");

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>


<%= render 'form' %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<%= link_to "Back",products_path %> | <%= link_to "Edit Product", edit_product_path(@product) %> | <%= link_to "Delete", @products, method: :delete, data: {confirm: "Delete yes or no??"}%>

<p><%= @product.name%>, <%=@product.formatted_price%></p>
<p><%= @product.description%></p>

<h3>Reviews</h3>
  <p>Reviews for <%= @product.name %></p>

<div class="review-list">
  <%= render :partial => "reviews" %>
</div>

<% if current_user %>
  <h4>New Review</h4>

  <%= form_for [@product, @review], :remote => true do |f| %>

  <div id="review-form-errors">
    <%= render "error" %>
  </div>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% else %>
  <p>Please <%= link_to "log in", new_sessions_path %> to add a review.</p>
<% end %>


<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
          $("input[type='submit']") // make changes to the submit button
            .val('Saving...') // change the text on the button
            .attr('disabled', 'disabled'); // disable the button
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $('#review-form-errors').html("<%= j (render(:partial => 'products/error')) %>");
<% else %>
  $('#review-form-errors').html("");
  $('.review-list').html("<%= escape_javascript(render(:partial => 'products/reviews'))%>")
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Whatever is written in the txtfield will be put to a variable :symbol. you can name it anything.s -->
  <div class="field">
    <%= f.label :name %> <br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %> <br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %> <br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %> <br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>